spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/checkmate_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: qwerqwreklasdkflakfekfqwerqwreklasdkflakfekf1234567890

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

openai:
  api-key: S15P02BD12-1c7941b4-ae8d-4789-afb0-fc3a57015f78
  model: gpt-4o-mini